version: '3'

services:
  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    platform: linux/x86_64
    ports: [ 1025, 1080 ]
  ###< symfony/mailer ###
  php:
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_MODE: "develop,debug,coverage"