monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - cscApi

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
                channels: [ "!event","!cscApi" ]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!cscApi"]
            cscApi:
                type: rotating_file
                path: '%kernel.logs_dir%/cscApi.log'
                level: info
                max_files: 5
                channels: cscApi

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!cscApi"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!cscApi"]
            cscApi:
                type: rotating_file
                path: '%kernel.logs_dir%/cscApi.log'
                level: info
                max_files: 5
                channels: cscApi

when@integration:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!cscApi"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!cscApi"]
            cscApi:
                type: rotating_file
                path: '%kernel.logs_dir%/cscApi.log'
                level: info
                max_files: 5
                channels: cscApi

when@prod: &prod
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
                channels: ["!cscApi"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!cscApi"]
                # formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine","!cscApi"]
            cscApi:
                type: rotating_file
                path: '%kernel.logs_dir%/cscApi.log'
                level: info
                max_files: 5
                channels: cscApi

#            deprecation:
#                type: stream
#                channels: [deprecation]
#                path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"

when@stage: *prod
